# config/sampler/default.yaml
T: ${forward.beta.T}
n_steps: 250
alloc_mode: "argmax"
score_from_classifier: true
score_scale: 1.0
force_classify_at_end: true
init_std: 1.0
eps_denom: 1e-12
rng_fold: 4